/*
Highly Divisible Triangular Number

The sequence of triangle numbers is generated by adding the natural 
numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28.
The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

1: 1
3: 1,3
6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over 
five hundred divisors?
*/

#include "ProjectEuler.h"

int divisorcount(int val);
void inctrianglenum(int* current, int n);
void primeFactors(int n);
int divisorcount(int num);

int primedivisors[2][10] = { 0 };

int main()
{
	int n = 28;
	int tri = 28;
	int* current = &tri;
	bool done = false;
	int divisors = 0;

	printf("%d\n", divisorcount(n));
	for (int i = 0; i < 2; i++)
	{
		for (int j = 0; j < 10; j++)
		{
			printf("%d ", primedivisors[i][j]);
		}
		printf("\n");
	}

	int trinum = 8;
	/*ile (tri < 200)
	{
		printf("%d ", tri);
		inctrianglenum(current, trinum);
		trinum++;
	}*/

	while (done == false)
	{
		divisors = divisorcount(tri);
		if (divisors > 500)
		{
			done = true;
			printf("%d", tri);
		}
		inctrianglenum(current, trinum);
		trinum++;
		for (int i = 0; i < 2; i++)
		{
			for (int j = 0; j < 10; j++)
			{
				primedivisors[i][j] = 0;
			}
		}

	}


		
}

int divisorcount(int num)
{
	int divisors = 1;
	int index = 0;
	primeFactors(num);
	while (primedivisors[1][index] != 0)
	{
		divisors *= (primedivisors[1][index] + 1);
		index++;
	}
	return divisors;
}
void inctrianglenum(int* current, int n)
{
	*current += n;
}

void primeFactors(int n)
{
	int index = 0;
	int count = 0;
	// Print the number of 2s that divide n
	if (n % 2 == 0)
	{
		primedivisors[0][index] = 2;

		while (n % 2 == 0)
		{
			n = n / 2;
			primedivisors[1][index]++;
		}
		index++;
	}

	// n must be odd at this point.  So we can skip one element (Note i = i +2)
	for (int i = 3; i*i <= n; i = i + 2)
	{
		if (n%i == 0)
		{
			primedivisors[0][index] = i;
			// While i divides n, print i and divide n
			while (n%i == 0)
			{
				n = n / i;
				primedivisors[1][index]++;
			}
			index++;
		}
	}

	// This condition is to handle the case whien n is a prime number
	// greater than 2
	if (n > 2)
	{
		primedivisors[0][index] = n;
		primedivisors[1][index]++;
		index++;
	}
}